language: python
python:
  - 3.6
services:
  - docker

script:
  - pip install flake8 && flake8 *.py pyouroboros/
  - python3 ./ouroboros -i 1 -l debug --run-once

deploy:
  - provider: pypi
    user: pyouroboros
    password: $PYPI_PASSWORD
    skip_existing: true
    on:
      branch: master

  - provider: script
    script: bash ./deploy.sh
    on:
      branch: master
