language: python
python:
  - 3.6
services:
  - docker

stages:
  - test
  - coverage
  - name: deploy
    if: branch = master

jobs:
include:
  - stage: test
    script: - ./run_tests.sh

  - stage: coverage
    script: - codecov

  - stage: deploy
    script: ./deploy