language: python
python:
  - 3.6
services:
  - docker

script:
  - ./run_tests.sh

after_script:
  - codecov

deploy:
  - provider: pypi
    user: circa10a
    password: $pypi_password
    skip_existing: true
    on:
      branch: master

  - provider: script
    script: bash ./deploy.sh
    on:
      branch: master