name: ouroboros_dev
dependencies:
  - pip:
      - docker
      - schedule
      - prometheus_client
      - requests
      - pytest
      - pytest-cov
      - pytest-mock
      - codecov
      - flake8